spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 57872182024-eqlac1aaaecfcbk1vppfadtd67ch9i16.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: http://localhost:8080/login/oauth2/code/google
            authorization-grant-type: authorization_code
            scope:
              - email
              - profile
jwt:
  secret: "DLWNDUDRLAGNLFODLACKSDNRHKRALSTJGHKDDBWLDKAGHZL"
  access:
    expirationMs: 1800000 #30분
  refresh:
    expirationMs: 2592000000 #30일