#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/onrank_db?useSSL=false&useUnicode=true&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
#    username: onrank
#    password: tocnfqkf@
#  sql:
#    init:
#      mode: always
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: create
#    properties:
#      hibernate:
#        format_sql: true
#    defer-datasource-initialization: true