spring:
  application:
    name: server
#  profiles:
#    include: cloud

server:
  forward-headers-strategy: framework

springdoc:
  cache:
    disabled: true

management:
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always